### ISSUE TITLE
No aparezco como contribuidor

### ISSUE THREAD

**Issue by alu0101130675** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct11-menu-api-grupo-i#1]
He hecho dos push y no salgo como contribuidor pero si se ve que he hecho commits en el historial. @esegredo @amarrerod

**Comment by amarrerod** [comment]
Has comprobado que el email y el nombre de usuario están bien configurados a la hora de hacer commits y push? @alu0101130675
