### ISSUE TITLE
Problema con patch

### ISSUE THREAD

**Issue by Nitro1000** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct11-menu-api-grupo-i#2]
A la hora de crear el método patch y probar con el thunder client al pasarle con un body o con Query un alimento nos salta el error 501 Not Implemented.
No se a que se debe y lo tenemos hecho para el alimento. Fichero [patch](https://github.com/ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct11-menu-api-grupo-i/blob/main/src/routers/patch.ts) @amarrerod @esegredo

**Comment by esegredo** [comment]
Hola @Nitro1000 , buenos días.

¿Han registrado patchRouter en la app?

Saludos.

**Comment by Nitro1000** [comment]
Buenas tardes profesor @esegredo.

En el fichero [server.ts](https://github.com/ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct11-menu-api-grupo-i/blob/main/src/server.ts) esta puesto el **app.use(patchRouter);** y su import **import {patchRouter} from './routers/patch';** como los demás comandos.

¿Se refiere a eso?

Saludos.

**Comment by esegredo** [comment]
Si, me refería a eso. ¿Están utilizando bien Thunder Client ,es decir, poniendo el método PATCH donde toca, además de especificar una ruta correcta como /ingredients, por ejemplo?

**Comment by esegredo** [comment]
Por cierto, tienen un problema con las rutas GET. Las que usan el parámetro :id no se deben especificar como '/ingredients: id', sino como '/ingredients/:id'.
